import{a as q,S as B,i}from"./assets/vendor-B5nsgUv9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const R="https://pixabay.com/api/",$="54763862-120f6024ab5c76e4f921b86ff";async function f(s,r){return(await q.get(R,{params:{key:$,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const p=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".load-more"),M=new B(".gallery a",{captionsData:"alt",captionDelay:250});function g(s){const r=s.map(({webformatURL:o,largeImageURL:c,tags:e,likes:t,views:a,comments:S,downloads:v})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${o}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${t}</p>
          <p><b>Views</b> ${a}</p>
          <p><b>Comments</b> ${S}</p>
          <p><b>Downloads</b> ${v}</p>
        </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",r),M.refresh()}function P(){p.innerHTML=""}function y(){h.classList.remove("is-hidden")}function b(){h.classList.add("is-hidden")}function L(){m.classList.remove("is-hidden")}function w(){m.classList.add("is-hidden")}const u=document.querySelector(".form"),O=document.querySelector(".load-more");let l="",n=1,d=0;u.addEventListener("submit",async s=>{s.preventDefault();const r=s.target.elements["search-text"].value.trim();if(!r){i.error({message:"Please enter a search query!",position:"topRight"});return}l=r,n=1,P(),w(),y();try{const o=await f(l,n);if(d=o.totalHits,o.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(o.hits),n*15<d?L():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({message:"Something went wrong!",position:"topRight"})}finally{b(),u.reset()}});O.addEventListener("click",async()=>{n+=1,y(),w();try{const s=await f(l,n);g(s.hits);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"}),n*15<d?L():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({message:"Something went wrong!",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
